services:
  reverse-proxy:
    image: nginx:alpine
    container_name: roar_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - waf-engine
      - backend-app
    networks:
      - waf-net

  waf-engine:
    build: .
    container_name: roar_engine
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - waf-net

  backend-app:
    image: traefik/whoami
    container_name: roar_victim
    networks:
      - waf-net

networks:
  waf-net:
    driver: bridge
