services:
  database:
    image: postgres:alpine
    container_name: roar_db
    environment:
      POSTGRES_USER: db_root
      POSTGRES_PASSWORD: db_password_123
      POSTGRES_DB: roar_waf
      TZ: Asia/Jakarta
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - waf-net

  reverse-proxy:
    image: nginx:alpine
    container_name: roar_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - waf-engine
      - backend-app
    networks:
      - waf-net

  waf-engine:
    build: .
    container_name: roar_engine
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgresql://db_root:db_password_123@database:5432/roar_waf
      TZ: Asia/Jakarta
    depends_on:
      - database
    networks:
      - waf-net

  backend-app:
    image: traefik/whoami
    container_name: roar_victim
    networks:
      - waf-net

networks:
  waf-net:
    driver: bridge

volumes:
  pgdata:
